### ISSUE TITLE
Add (or fix) live data BS step scans  

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/livedata#57]
Now, when BluSky step scanning works fine, we should add live data display for these data. It is Nexus file with some differences. Should not be difficult to modify existing code for Flyscanning. 
Data Collected 2-20-22 around 4:30-6pm, file names with "step" in them.

**Comment by prjemian** [comment]
One reason this issue has been hard to diagnose the root cause is that the VS Code debugger stopped supporting Python2.7.  At least for a time, there is a [work around](https://stackoverflow.com/questions/72214043/how-to-debug-python-2-7-code-with-vs-code) but this is not expected to remain a possibility long term.

Very important to continue on #48!

**Comment by prjemian** [comment]
To help diagnose this problem offline, need a conda/[micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html) environment with the correct package versions.  This one has worked so far on a couple example runs from 2022-12-17 & 18 to determine that `calc.reduce_uascan(sds)` does not raise any exceptions.

```yml
name: py2usaxs

# use:
#   date; micromamba create -y -n py2usaxs -f ./py2usaxs-env.yml; date
#   # then activate with:
#   eval "$(micromamba shell hook --shell=bash)"
#   micromamba activate py2usaxs

channels:
  - conda-forge
  - defaults
  # - aps-anl-tag
  # - apsu
  # - sveseli

dependencies:

  # --- Python core packages
  - python =2
  - h5py
  - lmfit
  - lxml
  - matplotlib
  - paramiko
  - pyepics
  - scipy
  - spec2nexus

  - ipython
  - jupyter

  # - pip:
  #   - happi
```
